spring:
  application:
    name: spring-cloud-stream-crashed
  cloud:
    bus:
      enabled: true
      id: ${spring.application.name:application}:${vcap.application.instance_id:0}

logging:
  level:
    com.ruinshe: DEBUG
